SOURCE=inc/*
LIB=lib/*
OUT=Servidor.out
TESTOUT=prueba.out
#OPTIONS = -IHeaders

main:
	g++ $(OPTIONS) -o $(OUT) $(SOURCE) $ main.cpp

run:
	./$(OUT)

test:
	g++ $(OPTIONS) -o $(TESTOUT) $(SOURCE) test.cpp
	./$(TESTOUT)

clean:
	rm $(OUT)
